name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.hello-action.outputs.time }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@ssulei7'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"

  deploy:
    runs-on: ubuntu-latest
    needs: test-action
    steps:
      - run: echo "${{ needs.test-action.outputs.time }} 
